spring:
  application:
    name: candidaturas

  # Conexão com o banco de dados
  # Variáveis de ambiente : ${NOME_VARIAVEL}
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Ao executar a aplicação, a JPA verifica se mudou algo nas classes e faz o update no banco de dados
  # create-drop (apaga ao desligar a aplicação)
  jpa:
    hibernate:
      ddl-auto: update

    # Consegue visualizar as operações realizadas no banco de dados
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Desabilitar o uso do docker compose.yaml para subir os containers
  docker:
    compose:
      enabled: false

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite

server:
  port: 8080

jwt:
  expiration: ${JWT_EXPIRATION:86400000} # 900000: 15 min
  key: ${JWT_KEY}